### ISSUE TITLE
Center the div

### ISSUE THREAD

**Issue by KrishnaDhingra** [mitp7/Fylo-LandingPage#1]
Hello,
The page looks great.
You might just want to center the 'Stay Productive wherever you are' content when it moves down on around 1056px.
I also had a question that from where did you get the 4 neon green outlined pictures?

**Comment by mitp7** [comment]
Ok thank you for the feedback I will make sure to change it. I think I found the images from here (https://css.gg/ or https://www.flaticon.com/ ) but feel free to fork this repo on to your system if you want the exact ones I used.
